FaceFinder.BackOffice/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FaceFinder.Data.DBContext;
using FaceFinder.Models.Entities;
using FaceFinder.Models.Api.Models;
using AutoMapper;
using FaceFinder.Data.Helpers;
using FaceFinder.BackOffice.Models;
using System.Threading.Tasks;
using Microsoft.ProjectOxford.Face;

namespace FaceFinder.BackOffice.Controllers
{
    public class PeopleController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: People
        public ActionResult Index()
        {
            var persons = db.Persons.Include(p => p.PersonGroup);
            return View(persons.ToList());
        }

        // GET: People/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.Persons.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // GET: People/Create
        public ActionResult Create()
        {
            //ViewBag.PersonGroupId = new SelectList(db.PersonGroups, "Id", "GroupGuid");
            return View();
        }

        // POST: People/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async System.Threading.Tasks.Task<ActionResult> Create([Bind(Include = "Id,FirstName,LastName,NickName,WantedReasons,Notes,Birthdate,Gender")] PersonVM model)
        {
            if (ModelState.IsValid)
            {
                string personGroupId = null;
                var config = new MapperConfiguration(cfg => cfg.CreateMap<PersonVM, Person>());
                var mapper = config.CreateMapper();
                var newPerson = mapper.Map<PersonVM, Person>(model);
                newPerson.DateRegistered = DateTime.UtcNow;
                db.Persons.Add(newPerson);
                db.SaveChanges();
                //return RedirectToAction("AddFaces", new { id = newPerson.Id });

                try
                {
                    var person = await FaceRecognitionHelper.CreatePerson(model.FirstName, newPerson.Id);
                    if (!person.Success)
                    {
                        ViewBag.Message = new MessageViewModel
                        {
                            IsError = true,
                            Message = "Favor intente más tarde, la base de datos de perfiles está siendo sincronizada"
                        };
                        db.Entry(newPerson).State = EntityState.Deleted;
                        db.SaveChanges();
                    }
                    else
                    {
                        newPerson.HasFacePersonId = true;
                        newPerson.FacePersonId = person.PersonId.ToString();
                        personGroupId = person.PersonGroupId.ToString();

                        newPerson.PersonGroupId = person.PersonGroupId;
                        db.Entry(newPerson).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("AddFaces", new { id = newPerson.Id });
                    }

                }
                catch (Exception e)
                {
                    //Roll back
                    db.Entry(newPerson).State = EntityState.Deleted;
                    db.SaveChanges();
                    //Delete Added Person
                    if (newPerson.PersonGroupId != null && newPerson.FacePersonId != null)
                    {
                        try
                        {
                            await FaceRecognitionHelper.DeletePerson(newPerson.FacePersonId, newPerson.PersonGroup.GroupGuid);

                        }
                        catch (Exception)
                        {
                            //TODO
                        }
                    }

                    ViewBag.Message = new MessageViewModel
                    {
                        IsError = true,
                        Message = "Favor intente más tarde, ha ocurrido un error tratando de crear el perfil"
                    };
                }

            }

            //ViewBag.PersonGroupId = new SelectList(db.PersonGroups, "Id", "GroupGuid", person.PersonGroupId);
            return View(model);
        }

        // GET: People/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.Persons.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            var config = new MapperConfiguration(cfg => cfg.CreateMap<Person, PersonVM>());
            var mapper = config.CreateMapper();
            var editPerson = mapper.Map<Person, PersonVM>(person);
            return View(editPerson);
        }

        // POST: People/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,NickName,WantedReasons,Notes,Birthdate,Gender,Disabled")] PersonVM person)
        {
            if (ModelState.IsValid)
            {
                var personEdited = db.Persons.Find(person.Id);
                personEdited.FirstName = person.FirstName;
                personEdited.LastName = person.LastName;
                personEdited.NickName = person.NickName;
                personEdited.WantedReasons = person.WantedReasons;
                personEdited.Notes = person.Notes;
                personEdited.Birthdate = person.Birthdate;
                personEdited.Gender = person.Gender;
                personEdited.Disabled = person.Disabled;
                db.Entry(personEdited).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(person);
        }

        // GET: People/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.Persons.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // POST: People/Delete/5
        [HttpPost, ActionName("Delete")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Person person = db.Persons.Include(p => p.FaceImages).FirstOrDefault(p => p.Id == id);
            if (person == null)
            {
                return HttpNotFound();
            }
            db.Persons.Remove(person);
            db.SaveChanges();
            foreach (var item in person.FaceImages)
            {
                await StorageHelper.DeleteImage(item.PersonId.ToString(), item.Id, item.Extension);
            }
            //TODO: Delete person in face api
            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }
        // GET: People/Faces/5
        public ActionResult Faces(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.Persons.Include(p => p.FaceImages).FirstOrDefault(p => p.Id == id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }
        // GET: People/AddFaces/5
        public ActionResult AddFaces(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.Persons.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // POST: People/AddFaces/5
        [HttpPost, ActionName("AddFaces")]
        public async System.Threading.Tasks.Task<ActionResult> AddFacesUpload(Person model)
        {
            if (model == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.Persons.Include(p => p.PersonGroup).FirstOrDefault(p => p.Id == model.Id);
            if (person == null)
            {
                return HttpNotFound();
            }
            for (int i = 0; i < Request.Files.Count; i++)
            {
                var file = Request.Files[i];
                var ext = System.IO.Path.GetExtension(file.FileName);
                int MaxContentLength = 1024 * 1024 * 4; //Size = 4 MB

                FaceImage image = new FaceImage
                {
                    PersonId = person.Id,
                    Extension = ext
                };
                db.FaceImages.Add(image);
                db.SaveChanges();
                var byteArray = StorageHelper.ConverToBytes(file);
                //Check file size, if is more than 4 MB, reduce it until get it
                if (byteArray.Length > MaxContentLength)
                {
                    byteArray = StorageHelper.ResizeImageFileSize(byteArray, MaxContentLength);
                }

FaceFinder.BackOffice/Controllers/UserProfilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FaceFinder.Data.DBContext;
using FaceFinder.Models.Entities;
using FaceFinder.Models.Api.Models;
using Microsoft.AspNet.Identity;
using FaceFinder.BackOffice.Models;
using Microsoft.AspNet.Identity.Owin;

namespace FaceFinder.BackOffice.Controllers
{
    public class UserProfilesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager _userManager;
        public UserProfilesController() { }

        public UserProfilesController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        // GET: UserProfiles
        public async Task<ActionResult> Index()
        {
            var userProfiles = db.UserProfiles.Include(u => u.ApplicationUser);
            return View(await userProfiles.ToListAsync());
        }

        // GET: UserProfiles/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userProfile = await db.UserProfiles.FindAsync(id);
            if (userProfile == null)
            {
                return HttpNotFound();
            }
            return View(userProfile);
        }

        // GET: UserProfiles/Create
        public ActionResult Create()
        {
            //ViewBag.ApplicationUserId = new SelectList(db.ApplicationUsers, "Id", "Email");
            return View();
        }

        // POST: UserProfiles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ApplicationUserId,FirstName,LastName,Email,Password")] UserModel userProfile)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = userProfile.Email, Email = userProfile.Email };
                var result = await UserManager.CreateAsync(user, userProfile.Password);
                if (result.Succeeded)
                {
                    var userRegistered = db.Users.FirstOrDefault(u => u.UserName == userProfile.Email);
                    db.UserProfiles.Add(new UserProfile
                    {
                        ApplicationUserId = userRegistered.Id,
                        DateRegistered = DateTime.UtcNow,
                        Disabled = false,
                        FirstName = userProfile.FirstName,
                        LastName = userProfile.LastName
                    });
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Message = new MessageViewModel
                    {
                        IsError = true,
                        Message = "Error al tratar de crear el usuario"
                    };
                }
            }
            return View(userProfile);
        }

        // GET: UserProfiles/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userProfile = await db.UserProfiles.Include(u => u.ApplicationUser).FirstOrDefaultAsync(u => u.ApplicationUserId == id);
            if (userProfile == null)
            {
                return HttpNotFound();
            }
            var resutl = new UserEditModel {
                ApplicationUserId = userProfile.ApplicationUserId,
                Disabled = userProfile.Disabled,
                Email = userProfile.ApplicationUser.Email,
                FirstName = userProfile.FirstName,
                LastName = userProfile.LastName
            };
            //ViewBag.ApplicationUserId = new SelectList(db.ApplicationUsers, "Id", "Email", userProfile.ApplicationUserId);
            return View(resutl);
        }

        // POST: UserProfiles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ApplicationUserId,FirstName,LastName,Email,Password,Disabled")] UserEditModel userProfile)
        {
            if (ModelState.IsValid)
            {
                var userRegistered = await db.UserProfiles.Include(p => p.ApplicationUser)
                    .FirstOrDefaultAsync(p => p.ApplicationUserId == userProfile.ApplicationUserId);
                userRegistered.ApplicationUser.Email = userProfile.Email;
                userRegistered.ApplicationUser.UserName = userProfile.Email;
                userRegistered.Disabled = userProfile.Disabled;
                userRegistered.FirstName = userProfile.FirstName;
                userRegistered.LastName = userProfile.LastName;
                if (!string.IsNullOrWhiteSpace(userProfile.Password))
                {
                    
                    await UserManager.RemovePasswordAsync(userRegistered.ApplicationUserId);
                    await UserManager.AddPasswordAsync(userRegistered.ApplicationUserId, userProfile.Password);
                }
                db.Entry(userRegistered).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            //ViewBag.ApplicationUserId = new SelectList(db.ApplicationUsers, "Id", "Email", userProfile.ApplicationUserId);
            return View(userProfile);
        }

        // GET: UserProfiles/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userProfile = await db.UserProfiles.FindAsync(id);
            if (userProfile == null)
            {
                return HttpNotFound();
            }
            return View(userProfile);
        }

        // POST: UserProfiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            UserProfile userProfile = await db.UserProfiles.FindAsync(id);
            db.UserProfiles.Remove(userProfile);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FaceFinder.BackOffice/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
@using FaceFinder.BackOffice.Models
@{
    bool? IsError = null;
    var Message = "";
    if (ViewBag.Message != null)
    {
        IsError = ((MessageViewModel)ViewBag.Message).IsError;
        Message = ((MessageViewModel)ViewBag.Message).Message;
    }
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewBag.Title - FaceFinder Admin Portal</title>
    <!-- Main styles for this application -->
    @*<link href="~/Content/bootstrap.css" rel="stylesheet" />*@
    <link href="~/Content/css/style.css" rel="stylesheet" />
    <link href="~/Content/css/sweetalert.css" rel="stylesheet" />
    @RenderSection("styles", required: false)
</head>
<!-- BODY options, add following classes to body to change options
    1. 'sidebar-nav'		  - Navigation on the left
        1.1. 'sidebar-off-canvas'	- Off-Canvas
            1.1.1 'sidebar-off-canvas-push'	- Off-Canvas which move content
            1.1.2 'sidebar-off-canvas-with-shadow'	- Add shadow to body elements
    2. 'fixed-nav'			  - Fixed navigation
    3. 'navbar-fixed'		  - Fixed navbar
-->
<body class="navbar-fixed sidebar-nav fixed-nav">
    <div id="pageSpinner" class="spinner" style="display:none;"></div>
    <!-- start: Layout Settings / remove this div from your project -->
    @*<div id="theme-settings" class="hidden-sm hidden-xs">
            <div id="open-close">
                <i class="fa fa-cog fa-spin"></i>
            </div>
            <h4>Options</h4>
            <hr>
            <ul id="options">
                <li>
                    <span class="desc">Fixed header</span>
                    <label class="switch switch-3d switch-sm switch-success pull-right">
                        <input type="checkbox" id="fixed-header" class="switch-input" checked>
                        <span class="switch-label"></span>
                        <span class="switch-handle"></span>
                    </label>
                </li>
                <li>
                    <span class="desc">Sidebar navigation</span>
                    <label class="switch switch-3d switch-sm switch-success pull-right">
                        <input type="checkbox" id="sidebar-navigation" class="switch-input" checked>
                        <span class="switch-label"></span>
                        <span class="switch-handle"></span>
                    </label>
                </li>
                <li>
                    <span class="desc">Fixed navigation</span>
                    <label class="switch switch-3d switch-sm switch-success pull-right">
                        <input type="checkbox" id="fixed-navigation" class="switch-input" checked>
                        <span class="switch-label"></span>
                        <span class="switch-handle"></span>
                    </label>
                </li>
                <li>
                    <span class="desc">Hidden sidebar</span>
                    <label class="switch switch-3d switch-sm switch-success pull-right">
                        <input type="checkbox" id="hidden-sidebar" class="switch-input">
                        <span class="switch-label"></span>
                        <span class="switch-handle"></span>
                    </label>
                </li>
            </ul>
        </div>*@
    <!-- end: Layout Settings -->
    <header class="navbar">
        <div class="container-fluid">
            <button class="navbar-toggler mobile-toggler hidden-lg-up" type="button">&#9776;</button>
            <a class="navbar-brand" href="#"></a>
            <ul class="nav navbar-nav hidden-md-down">
                <li class="nav-item">
                    <a class="nav-link navbar-toggler layout-toggler" href="#">☰</a>
                </li>
                <li class="nav-item p-x-1">
                    <span class="nav-link">FaceFinder - Sistema de identificación de perfiles.</span>
                </li>
                @*@if (IsAgent)
                    {
                        <li class="nav-item p-x-1">
                            <a class="nav-link" href="#">Dashboard</a>
                        </li>
                    }
                    @if (IsAdmin)
                    {
                        <li class="nav-item p-x-1">
                            <a class="nav-link" href="#">Users</a>
                        </li>
                    }
                    <li class="nav-item p-x-1">
                        <a class="nav-link" href="#">Settings</a>
                    </li>
                *@
            </ul>
            <ul class="nav navbar-nav pull-right hidden-md-down">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                        <img src="~/Content/img/avatars/6.jpg" class="img-avatar" alt="admin@bootstrapmaster.com">
                        <span class="hidden-md-down">Opciones de usuario</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <div class="dropdown-header text-xs-center">
                            <strong>Cuenta</strong>
                        </div>
                        @if (Request.IsAuthenticated)
                        {
                            using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                            {
                                @Html.AntiForgeryToken()
                                <a class="dropdown-item" href="javascript:document.getElementById('logoutForm').submit()"><i class="fa fa-lock"></i> Logout</a>
                            }
                        }

                    </div>
                </li>
            </ul>
        </div>
    </header>
    <div class="sidebar">
        <nav class="sidebar-nav">
            <ul class="nav">
                <li class="nav-title">
                    Dashboard
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Home")"><i class="icon-speedometer"></i> DASHBOARD</a>
                </li>
                <li class="divider"></li>
                @if (IsAdmin)
                {
                    <li class="nav-title">
                        Opciones
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "People")"><i class="icon-people"></i> Perfiles</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "UserProfiles")"><i class="icon-shield"></i> Usuarios</a>
                    </li>
                }

                @*<li class="nav-item">
                        <a class="nav-link" href="#"><i class="icon-bell"></i> Alertas</a>
                    </li>*@
            </ul>
        </nav>
    </div>
    <!-- Main content -->
    <main class="main">
        <div class="container-fluid">
            <div class="animated fadeIn">
                @RenderBody()
            </div>
        </div>
        <!-- /.conainer-fluid -->
    </main>
    <footer class="footer ng-scope">
        <span class="pull-right text-muted">
            Angel Garcia © @DateTime.Now.Year
        </span>
    </footer>
    @{
        if (IsError != null)
        {
            <span id="IsError" style="visibility: hidden;display:none">@IsError</span>
            <span id="Message" style="visibility: hidden;display:none">@Message</span>
        }

    }
    <!-- The Modal -->
    <div id="myModal" class="modal">

        <!-- The Close Button -->
        <span class="close" onclick="document.getElementById('myModal').style.display='none'">&times;</span>

        <!-- Modal Content (The Image) -->
        <img class="modal-content" id="img01">

        <!-- Modal Caption (Image Text) -->
        <div id="caption"></div>
    </div>
    <!-- Bootstrap and necessary plugins -->
    <script src="~/Scripts/js/libs/jquery.min.js"></script>
    <script src="~/Scripts/js/libs/tether.min.js"></script>
    <script src="~/Scripts/js/libs/bootstrap.min.js"></script>
    <script src="~/Scripts/js/libs/pace.min.js"></script>
    <!-- Plugins and scripts required by all views -->
    <script src="~/Scripts/js/libs/Chart.min.js"></script>
    <script src="~/Scripts/js/views/shared.js"></script>
    <script src="~/Scripts/js/libs/sweetalert.min.js"></script>
    <!-- GenesisUI main scripts -->
    <script src="~/Scripts/js/app.js"></script>
    <script src="~/Scripts/js/app-options.js"></script>
    <!--Custom Js-->
    <script src="~/Scripts/js/nautJs.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>